name: Release

on:
  push:
    tags:
      - "test*"
  pull_request:
    paths:
      - '!**/README.md'
  workflow_dispatch:

jobs:
  SignatureVerificationTool:
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: macOS-latest
            runtime: osx-arm64
          - os: ubuntu-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: linux-arm
          - os: ubuntu-latest
            runtime: linux-arm64
          - os: ubuntu-latest
            runtime: linux-musl-x64
          - os: ubuntu-latest
            runtime: linux-musl-arm
          - os: ubuntu-latest
            runtime: linux-musl-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build SignatureVerificationTool
        run: cd SignatureVerificationTool && dotnet publish --runtime ${{ matrix.runtime }} --configuration Release --self-contained true --output build_output

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DDTV-Server-${{ matrix.os }}-${{ matrix.runtime }}
          path: SignatureVerificationTool/build_output

